import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Wail Solaiman</title>
        <meta name="description" content="Generated by create next app" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#747575" />
        <meta name="msapplication-TileColor" content="#603cba" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <div>
        <p>Hello World!</p>
      </div>
    </div>
  )
}

export default Home
